"""empty message

Revision ID: 2446ee739caa
Revises: 585072adddcd
Create Date: 2015-10-18 14:43:18.021242

"""

# revision identifiers, used by Alembic.
revision = '2446ee739caa'
down_revision = '585072adddcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
