"""empty message

Revision ID: 575795fa3a07
Revises: 38c4e85512a9
Create Date: 2015-10-21 14:46:32.060411

"""

# revision identifiers, used by Alembic.
revision = '575795fa3a07'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
