"""empty message

Revision ID: 5802c683b724
Revises: 3d7269775db5
Create Date: 2015-10-22 22:47:25.044108

"""

# revision identifiers, used by Alembic.
revision = '5802c683b724'
down_revision = '3d7269775db5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
