"""empty message

Revision ID: 585072adddcd
Revises: 54cb852c2478
Create Date: 2015-10-17 17:44:07.457007

"""

# revision identifiers, used by Alembic.
revision = '585072adddcd'
down_revision = '54cb852c2478'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
